### ISSUE TITLE
unexpected error: Error: Unexpected pending rebuildTimer

### ISSUE THREAD

**Issue by ChuckJonas** [yunabe/tslab#87]
Trying to follow instructions for `tslab-plotly` and get this error:

```
unexpected error: Error: Unexpected pending rebuildTimer
    at Object.sys.setTimeout (/Users/foo/.nvm/versions/node/v16.19.0/lib/node_modules/tslab/dist/converter.js:111:19)
    at scheduleProgramUpdate (/Users/foo/.nvm/versions/node/v16.19.0/lib/node_modules/tslab/node_modules/@tslab/typescript-for-tslab/lib/typescript.js:122735:35)
    at onSourceFileChange (/Users/foo/.nvm/versions/node/v16.19.0/lib/node_modules/tslab/node_modules/@tslab/typescript-for-tslab/lib/typescript.js:122876:7)
    at /Users/foo/.nvm/versions/node/v16.19.0/lib/node_modules/tslab/node_modules/@tslab/typescript-for-tslab/lib/typescript.js:122868:56
    at updateContent (/Users/foo/.nvm/versions/node/v16.19.0/lib/node_modules/tslab/dist/converter.js:601:9)
    at Object.convert (/Users/foo/.nvm/versions/node/v16.19.0/lib/node_modules/tslab/dist/converter.js:252:9)
    at Object.execute (/Users/foo/.nvm/versions/node/v16.19.0/lib/node_modules/tslab/dist/executor.js:138:38)
    at JupyterHandlerImpl.handleExecuteImpl (/Users/foo/.nvm/versions/node/v16.19.0/lib/node_modules/tslab/dist/jupyter.js:223:38)
    at /Users/foo/.nvm/versions/node/v16.19.0/lib/node_modules/tslab/dist/jupyter.js:181:57
    at async JupyterHandlerImpl.handleExecute (/Users/foo/.nvm/versions/node/v16.19.0/lib/node_modules/tslab/dist/jupyter.js:181:21)
    ```

**Comment by ChuckJonas** [comment]
nvm, user error

**Comment by mzlzyCA** [comment]
> nvm, user error
hi, I get the same error as you, how did you fix this?
